name: "<arrow-library>: build documentation"

on: pull_request

jobs:
  <arrow-library>_build_documentation:

    env:
      BASEDIR: ${{github.workspace}}/..
      JAVA_OPTS: -Xms512m -Xmx1024m
      ARROW_LIB: <arrow-library>

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - name: Generate API doc and validate
      run: ./gradlew buildArrowDoc
