name: "Check Build Integration"

on:
  pull_request:
    paths-ignore:
    - 'docs/**'
    - 'templates/**'
    - '**.md'

jobs:
  check-build-integration:

    env:
      BASEDIR: ${{github.workspace}}/..
      JAVA_OPTS: -Xms512m -Xmx1024m

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - name: Check
      run: ./scripts/check-build-integration.sh
